version: '3'

services:
  application:
    image: nehashirsat/linuxos:v1.0.0
    ports:
      - "9000:9000"
    links:
      - database
  database:
      image: mysql:latest
      ports:
        - "3306:3306"
